
import { useSupabaseListaCompras } from "./useSupabaseListaCompras";
import { toast } from "sonner";

export function useListaCompras() {
  const {
    itensCompra: itensPorRefeicao,
    adicionarItem,
    atualizarItem,
    removerItem: removerItemSupabase
  } = useSupabaseListaCompras();

  const toggleItem = async (refeicao: string, itemId: string) => {
    const item = itensPorRefeicao[refeicao]?.find(item => item.id === itemId);
    if (!item) return;

    const novoStatus = !item.comprado;
    await atualizarItem(refeicao, itemId, { comprado: novoStatus });
    
    if (novoStatus) {
      toast.success(`'${item.nome}' marked as purchased! ✅`);
    }
  };

  const toggleTodosItens = async (refeicao: string) => {
    const itens = itensPorRefeicao[refeicao] || [];
    const todosComprados = itens.every(item => item.comprado);
    
    for (const item of itens) {
      await atualizarItem(refeicao, item.id, { comprado: !todosComprados });
    }
    
    toast.success(todosComprados ? "All items unchecked" : "All items marked as purchased!");
  };

  const removerItem = async (refeicao: string, itemId: string) => {
    await removerItemSupabase(refeicao, itemId);
  };

  const removerItensSelecionados = async (refeicao: string) => {
    const itens = itensPorRefeicao[refeicao] || [];
    const itensComprados = itens.filter(item => item.comprado);
    
    if (itensComprados.length === 0) {
      toast.error("No items selected to remove!");
      return;
    }

    for (const item of itensComprados) {
      await removerItemSupabase(refeicao, item.id);
    }
    
    toast.success(`${itensComprados.length} item(s) removed from list!`);
  };

  const calcularTotalRefeicao = (refeicao: string) => {
    const itens = itensPorRefeicao[refeicao] || [];
    return itens.reduce((total, item) => total + item.preco, 0);
  };

  const calcularTotalGeral = () => {
    return Object.values(itensPorRefeicao).flat().reduce((total, item) => total + item.preco, 0);
  };

  const exportarLista = () => {
    const dadosExport = Object.entries(itensPorRefeicao).map(([refeicao, itens]) => ({
      refeicao,
      itens: itens.map(item => ({
        nome: item.nome,
        quantidade: item.quantidade,
        preco: item.preco,
        comprado: item.comprado ? "Yes" : "No"
      })),
      total: calcularTotalRefeicao(refeicao)
    }));

    console.log("Exporting list:", dadosExport);
    toast.success("List exported successfully! 📊");
  };

  const adicionarItensGerados = async (refeicao: string, novosItens: any[]) => {
    for (const item of novosItens) {
      const novoItem = {
        id: '', // Will be generated by Supabase
        nome: item.nome,
        quantidade: item.quantidade,
        preco: item.preco,
        comprado: false,
        categoria: item.categoria || undefined
      };
      await adicionarItem(refeicao, novoItem);
    }
  };

  const adicionarItemSugerido = async (refeicao: string, nomeItem: string) => {
    const novoItem = {
      id: '', // Will be generated by Supabase
      nome: nomeItem,
      quantidade: "1 unit",
      preco: Math.floor(Math.random() * 20) + 5,
      comprado: false
    };
    await adicionarItem(refeicao, novoItem);
  };

  return {
    itensPorRefeicao,
    toggleItem,
    toggleTodosItens,
    calcularTotalRefeicao,
    calcularTotalGeral,
    exportarLista,
    adicionarItensGerados,
    adicionarItemSugerido,
    removerItem,
    removerItensSelecionados
  };
}
