// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydbwjupiouzylanfrldv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkYndqdXBpb3V6eWxhbmZybGR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODc4OTUsImV4cCI6MjA2NDQ2Mzg5NX0.0v6WA5FzcIU8SlZsjJxueAUJWQhtWzftUKOqq9nyk0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);